# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X cmd.version={{.Version}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: youheiyouhei
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    caveats: |
      Thanks for installing Transgo!

      Before you can start translating, make sure to configure your DeepL API key:
      $ transgo config --set api_key=YOUR_API_KEY

      For further details and usage, refer to our documentation at https://github.com/youheiyouhei/transgo
    homepage: "https://example.com"
    description: "Transgo CLI tool for translations."
    dependencies:
      - name: git
