name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run go fmt
      run: |
        GOFMT_FILES=$(go fmt ./...)
        if [ -n "$GOFMT_FILES" ]; then
          echo "The following files need to be formatted:"
          echo "$GOFMT_FILES"
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Run go test
      run: go test ./...
